src/modules/ExtensionPhoneNumber/index.js

add SmsSender filter to ExtensionPhoneNumber modules

add smsSenderNumbers to extensionNumber

---

src/modules/AccountExtension/actionTypes.js
src/modules/AccountExtension/index.js

add update to account extension actiontypes

add update to account extension actiontypes

---

src/lib/validateAreaCode.js
src/lib/validateAreaCode.test.js
src/modules/RegionSettings/index.js

refactor validateAreaCode

---

dev-server/index.js
src/modules/NumberValidate/getNumberValidateReducer.js
src/modules/NumberValidate/index.js
src/modules/NumberValidate/numberValidateActionTypes.js

add number validate module

---

dev-server/index.js
src/lib/isBlank.js
src/lib/isBlank.test.js
src/modules/ComposeText/composeTextActionTypes.js
src/modules/ComposeText/composeTextStatus.js
src/modules/ComposeText/getCacheReducer.js
src/modules/ComposeText/getCacheReducer.test.js
src/modules/ComposeText/getComposeTextReducer.js
src/modules/ComposeText/getComposeTextReducer.test.js
src/modules/ComposeText/index.js
src/modules/ComposeText/index.test.js
src/modules/MessageSender/getMessageSenderReducer.js
src/modules/MessageSender/getMessageSenderReducer.test.js
src/modules/MessageSender/index.js
src/modules/MessageSender/index.test.js
src/modules/MessageSender/messageSenderActionTypes.js
src/modules/MessageSender/messageSenderMessages.js
src/modules/MessageSender/messageSenderStatus.js
src/modules/NumberValidate/index.js

add message sender module
add compost text module

add message sender module and compose text module

---

.travis.yml
gulpfile.js
scripts/prepare_release.sh
scripts/release.sh
scripts/start_release.sh

auto publish npm packeage when tag

auto publish npm packeage when tag

---

.travis.yml
gulpfile.js

not push to latest branch when add a tag

not push to latest branch when add a tag

---

gulpfile.js

log tag and version for test ci npm publish

log tag and version for test ci npm publish

---

.travis.yml
gulpfile.js
package.json

skip_cleanup set to true when publish to npm
set description

skip_cleanup set to true when publish to npm

---

README.md
dev-server/index.js
src/lib/batchApiHelper.js
src/lib/messageHelper.js
src/lib/messageHelper.test.js
src/modules/MessageStore/getCacheReducer.js
src/modules/MessageStore/getCacheReducer.test.js
src/modules/MessageStore/getMessageStoreReducer.js
src/modules/MessageStore/getMessageStoreReducer.test.js
src/modules/MessageStore/index.js
src/modules/MessageStore/index.test.js
src/modules/MessageStore/messageStoreActionTypes.js
src/modules/MessageStore/messageStoreHelper.js
src/modules/MessageStore/messageStoreHelper.test.js
src/modules/MessageStore/messageStoreStatus.js

add message store module

---

README.md
dev-server/index.js
src/modules/Messages/getMessagesReducer.js
src/modules/Messages/getMessagesReducer.test.js
src/modules/Messages/index.js
src/modules/Messages/index.test.js
src/modules/Messages/messagesActionTypes.js

add messages module

---

dev-server/index.js
src/modules/Conversation/conversationActionTypes.js
src/modules/Conversation/conversationStatus.js
src/modules/Conversation/getConversationReducer.js
src/modules/Conversation/getConversationReducer.test.js
src/modules/Conversation/index.js
src/modules/Conversation/index.test.js

add conversation module

---

dev-server/index.js
src/modules/ContactSearch/contactSearchActionTypes.js
src/modules/ContactSearch/contactSearchStatus.js
src/modules/ContactSearch/getCacheReducer.js
src/modules/ContactSearch/getCacheReducer.test.js
src/modules/ContactSearch/getContactSearchReducer.js
src/modules/ContactSearch/getContactSearchReducer.test.js
src/modules/ContactSearch/index.js
src/modules/ContactSearch/index.test.js

add contactSearch module

---

src/modules/MessageSender/index.js
src/modules/NumberValidate/index.js
src/modules/NumberValidate/index.test.js

add test for number validate module

---

README.md
dev-server/index.js
src/integration-test/commons/Phone/index.js
src/integration-test/spec-modules/composeText.js

add messageStore, messages and conversation module to integration test phone.js

add messageStore, messages and conversation module to integration test phone.js

---

src/integration-test/spec-modules/numValidInCall.js
src/lib/cleanNumber/cleanNumber.test.js
src/lib/cleanNumber/index.js
src/modules/Call/actionTypes.js
src/modules/Call/getCallReducer.js
src/modules/Call/getCallReducer.test.js
src/modules/Call/index.js
src/modules/Ringout/actionTypes.js
src/modules/Ringout/getRingoutReducer.js
src/modules/Ringout/getRingoutReducer.test.js
src/modules/Ringout/index.js

fix RCINT-3495 : change completeConnect action to connectSuccess and connectError
fix RCINT-3496 : check invalid char when validating toNumber;

fix RCINT-3495 RCINT-3496

---

src/modules/MessageStore/index.js
src/modules/MessageStore/index.test.js

allow sms message subject to be undefined

allow sms message subject to be undefined

---

src/modules/MessageStore/messageStoreHelper.js

fix bug when message is deleted

fix bug when message is deleted

---

src/integration-test/spec-modules/composeText.js
src/modules/Conversation/index.js
src/modules/Conversation/index.test.js
src/modules/MessageSender/index.js
src/modules/MessageSender/index.test.js
src/modules/MessageStore/index.js

change message sender response to responses
to support different redirect url when responses length more than one

change message sender response to responses

---

src/integration-test/spec-modules/composeText.js

fix integration test

---

dev-server/index.js
src/integration-test/commons/Phone/index.js
src/integration-test/spec-modules/composeText.js
src/modules/Call/index.js
src/modules/MessageSender/index.js
src/modules/MessageSender/index.test.js
src/modules/NumberValidate/index.js
src/modules/NumberValidate/index.test.js

call use numberValidate module to validate numbers (#213 )
message sender allow to send pager to mainCompanyNumber*extension

call use numberValidate module to validate numbers

---

src/lib/DataMatcher/index.js
src/modules/MessageStore/index.js
src/modules/Messages/index.js

add contact matcher to messages
add dataMapping to dataMatcher

add contact matcher to messages

---

src/modules/Messages/index.js
src/modules/Messages/index.test.js

auto trigger match when messages updated
delete normalizedMessages

auto trigger match when messages updated

---

src/lib/DataMatcher/index.js

fix bug of dataMapping

---

src/lib/DataMatcher/index.js

Bugfix datamatcher datamapping

Bugfix datamatcher datamapping

---

src/modules/Conversation/index.js
src/modules/Conversation/index.test.js
src/modules/MessageSender/index.js

add changeMatchedNames to conversation

add changeMatchedNames to conversation

---

src/lib/messageHelper.js
src/lib/messageHelper.test.js
src/modules/Conversation/index.js
src/modules/Conversation/index.test.js
src/modules/MessageStore/index.js
src/modules/MessageStore/messageStoreHelper.js
src/modules/MessageStore/messageStoreHelper.test.js
src/modules/Messages/index.js
src/modules/Messages/index.test.js

add voicemail and fax message to messageStore

add voicemail and fax message to message store

---

src/lib/DataFetcher/index.js
src/modules/Brand/index.js
src/modules/RolesAndPermissions/index.js
src/modules/RolesAndPermissions/permissionsMessages.js

Re-use Salesforce flag in Admin Web to control tiers to access RC for Dynamics app

Rcint 4010

---

.eslintrc

import/extensions lint plugin have problem on import module from node_modules

turn off import/extensions lint plugin

---

src/modules/RolesAndPermissions/index.js
src/modules/Webphone/index.js

enhancement of web phone permission.

enhancement of web phone permission

---

package.json
src/modules/AccountExtension/accountExtensionHelper.js
src/modules/AccountExtension/index.js
src/modules/AccountExtension/index.test.js
yarn.lock

Test account extension

---

dev-server/index.js
src/modules/ExtensionDevice/index.js

add extension device module

---

dev-server/Phone.js
src/modules/Contacts/index.js
src/modules/Webphone/index.js

add contacts as contact matcher source
web phone new call trigger match

add contacts as contact matcher source

---

demo-extension/webpack.config.js
dev-server/Phone.js
dev-server/webpack.config.js
src/modules/Call/index.js
src/modules/Webphone/getWebphoneReducer.js
src/modules/Webphone/getWebphoneReducer.test.js
src/modules/Webphone/index.js
src/modules/Webphone/webphoneErrors.js

use file loader to load ogg file
check DL before connect
remember error code when connect web phone

Enhancement web phone module

---

src/modules/Call/index.js
src/modules/Call/index.test.js
src/modules/Webphone/index.js
src/modules/Webphone/webphoneErrors.js

verify DL when make call and connect
fix bug on call module to rename _initModule

verify DL when make call and connect

---

src/modules/Webphone/index.js

add onCallStart to web phone

---

src/modules/Webphone/index.js

allow to forward 7-digit number

allow to forward 7-digit number if user set area code

---

src/modules/RegionSettings/index.js

fix error in checkRegionSettings

---

dev-server/Phone.js
src/modules/RecentMessages/actionTypes.js
src/modules/RecentMessages/getRecentMessagesReducer.js
src/modules/RecentMessages/getRecentMessagesReducer.test.js
src/modules/RecentMessages/index.js
src/modules/RecentMessages/messageStatus.js

Used in messages tab on recent activities panel.

Create recent messages module

---

src/lib/Analytics/segment.js
src/modules/CallLogger/index.js
src/modules/CallMonitor/index.js
yarn.lock

add toNumberEntity into callLogger and let call module is not hard dependency of CallMonitor

add toNumberEntity into callLogger

---

dev-server/Phone.js
src/modules/AddressBook/index.js
src/modules/MessageStore/index.js
src/modules/MessageStore/messageStoreHelper.js

to handle with:
https://github.com/ringcentral/ringcentral-js-widget/issues/95
https://github.com/ringcentral/ringcentral-js-widget/issues/96

enhancement of message store to handle 429 and network problem

---

dev-server/Phone.js
src/modules/Subscription/index.js

fix wrong event filters when register.
resubscribe when network is back online.

fix bugs of wrong event filters and network back online

---

src/modules/ComposeText/getComposeTextReducer.js
src/modules/ComposeText/getComposeTextReducer.test.js
src/modules/ComposeText/index.js

when phone number is exist in toNumber array, pass new entity id should replace in the array
prevent state from being mutated

RCINT-4901

---

README.md
docs/creating-modules.md

update creating modules docs

---

src/modules/CallLog/index.js

…when an incoming call is sent to voicemail

RCINT-5111An outbound call to user's own number is shown in history when an incoming call is sent to voicemail

---

package.json
src/modules/ContactSearch/getContactSearchReducer.js
src/modules/ContactSearch/getContactSearchReducer.test.js
src/modules/ContactSearch/index.js

* fixed a contact lowercase first letter repeating group bug
* add yarn unit-test command for UT a single file(yarn unit-test ${path})
* fixed clean up contact list data when logout

Fixed contacts group bug and clear contacts when logout

---

package.json
src/modules/ContactSearch/actionTypes.js
src/modules/ContactSearch/getContactSearchReducer.js
src/modules/ContactSearch/index.js
yarn.lock

* previous account's contact filter setting will affect next account's setting
* add `yarn prettier`  it can code format (configurable for pre-commit)

Fixed clear filter when logout and add `prettier` for code formatter

---

src/modules/AddressBook/index.js
src/modules/ContactSearch/index.js

* fixed some special characters will be escaped
* compose text 's search result affect contacts panel

fixed escaped contacts text and compose search affect contacts

---

src/modules/AccountContacts/index.js
src/modules/ContactDetails/index.js
src/modules/Contacts/index.js

disable useCache when fetch profile image and presence on contact detail

disable useCache when fetch profile image and presence on contact detail

---

.editorconfig
.gitattributes
.vscode/settings.json

Added config for eol to make sure it keeps consistent across OS

enforce eol format to lf

---

src/integration-test/commons/Phone/index.js
src/integration-test/spec-modules/numValidInCall.js
src/integration-test/utils/HelpUtil.js
src/modules/MessageStore/index.test.js

fix message store test

---

src/integration-test/commons/Phone/index.js
src/integration-test/commons/TestPhoneFactory.js
src/integration-test/commons/specs/commons.spec.js
src/integration-test/mock/data/blockedNumber.json
src/integration-test/mock/data/forwardingNumber.json
src/integration-test/mock/index.js
src/integration-test/spec-modules/blockedNumber.js
src/integration-test/spec-modules/forwardingNumber.js
src/integration-test/utils/HelpUtil.js
src/lib/DataFetcher/getDataFetcherReducer.js
src/lib/DataFetcher/getDataFetcherReducer.test.js
src/lib/DataFetcher/index.js
src/lib/getter.js
src/modules/BlockedNumber/index.js
src/modules/ForwardingNumber/index.js
src/modules/RolesAndPermissions/index.js

enhancement: permission check in blockNumber and forwardingNumber
fix bugs on getter library

enhancement: permission check in blockNumber and forwardingNumber

---

src/integration-test/commons/Phone/index.js
src/integration-test/commons/specs/commons.spec.js
src/integration-test/mock/data/accountPhoneNumber.json
src/integration-test/mock/index.js
src/integration-test/spec-modules/accountExtension.js
src/integration-test/spec-modules/accountInfo.js
src/integration-test/spec-modules/accountPhoneNumber.js
src/integration-test/spec-modules/dialingPlan.js
src/integration-test/spec-modules/extensionInfo.js
src/integration-test/spec-modules/forwardingNumber.js
src/integration-test/spec-modules/rolesAndPermissions.js
src/lib/DataFetcher/index.js
src/modules/AccountExtension/index.js
src/modules/AccountInfo/index.js
src/modules/AccountPhoneNumber/getReducer.js
src/modules/AccountPhoneNumber/index.js
src/modules/DialingPlan/index.js
src/modules/ExtensionInfo/index.js
src/modules/ForwardingNumber/index.js
src/modules/RolesAndPermissions/index.js
src/modules/RolesAndPermissions/permissionsMessages.js

Enhancement of permission check in
* ExtensionInfo
* AccountInfo
* RolesPermissions
* ForwardingNumber
* AccountPhoneNumber
* DialingPlan
* AccountExtension
Add forbiddenHandler to DataFetcher
Add integration tests

enhancement of permission check in ExtensionInfo,AccountInfo,RolesPermissions
